In [ ]:
import sys
sys.path.append('..')  # cis1/ root

from src import Tracker, Frame, vct3, Rot
import numpy as np

tracker = Tracker("example_tracker")
frame = Frame(Rot(matrix=np.eye(3)), vct3(0, 0, 0))
cov = np.eye(3) 
tracker.create(frame, cov)
print(tracker)

Tracker(name='example_tracker', F=Frame(R=Rot(matrix=
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]), p=vct3(x=0.00, y=0.00, z=0.00)
Internal Vector:
[[0.]
 [0.]
 [0.]]), C=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))


In [2]:
# set pose method
frame = Frame(Rot(axis='x', angle=30), vct3(1, 1, -1))
tracker.set_pose(frame)

Tracker(name='example_tracker', F=Frame(R=Rot(matrix=
[[ 1.          0.          0.        ]
 [ 0.          0.15425145  0.98803162]
 [ 0.         -0.98803162  0.15425145]]), p=vct3(x=1.00, y=1.00, z=-1.00)
Internal Vector:
[[ 1.]
 [ 1.]
 [-1.]]), C=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))

In [3]:
# set covariance method
cov = [[1, 0, 0], [0, -1, 0], [0, 0, -1]]
tracker.set_cov(cov)

Tracker(name='example_tracker', F=Frame(R=Rot(matrix=
[[ 1.          0.          0.        ]
 [ 0.          0.15425145  0.98803162]
 [ 0.         -0.98803162  0.15425145]]), p=vct3(x=1.00, y=1.00, z=-1.00)
Internal Vector:
[[ 1.]
 [ 1.]
 [-1.]]), C=[[1, 0, 0], [0, -1, 0], [0, 0, -1]])

In [ ]:
# add markers from the marker body object
markers = [vct3(1, 1, 1), vct3(2, 2, 2), vct3(3, 3, 3)]
tracker.read_markers(markers)

Marker position in tracker frame: [ 0.         -1.97606325  0.3085029 ]
Marker position in tracker frame: [ 1.         -2.80984342  1.45078597]
Marker position in tracker frame: [ 2.         -3.6436236   2.59306905]


/home/eng/repos/mt_ml_tools/cis1/utils.py:10: RuntimeWarning: covariance is not symmetric positive-semidefinite.
  return np.random.multivariate_normal(mean, cov, n)


[array([[ 1.28864138, -1.40457571, -0.84976658]]),
 array([[ 1.2962804 , -1.74992885,  1.11305145]]),
 array([[ 2.16249255, -5.72775645,  1.36281559]])]